import type { Metadata } from "next";
import "./globals.css";
import { EuclidSquare, EuclidTriangle, GeistMono, suit, suite } from "./font";
import { Header } from "../common/Header";

export const metadata: Metadata = {
  title: "BuildX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${EuclidSquare.variable} ${EuclidTriangle.variable} ${GeistMono.variable} ${suit.variable} ${suite.variable}`}
    >
      <body>
        <div className="flex flex-col items-center">
          <Header />
          <div className="flex flex-col w-full px-10 lg:max-w-[1280px] items-center pt-20 mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
